HW19_2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users'))
]

catalog/urls.py
from operator import index

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ContactsListView, IndexListView, BlogListView, BlogCreateView, \
    BlogDetailView, BlogUpdateView, BlogDeleteView, ProductUpdateView, ProductDeleteView, ProductDetailView, ProductCreateView

app_name = CatalogConfig.name





urlpatterns = [
    path('', IndexListView.as_view(), name='index'),
    path('product/', ProductListView.as_view(), name='product'),
    path('contacts/', ContactsListView.as_view(), name='contacts'),
    path('blog_list/', BlogListView.as_view(), name='blog_list'),
    path('blog_create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog_detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog_update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog_delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
    path('product_create/', ProductCreateView.as_view(), name='product_create'),
    path('product_detail/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('product_update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product_delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, ProfileView, generate_new_password, \
    UserConfirmationSentView, UserVerifyEmailView, UserConfirmedView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('email_confirm/', UserConfirmationSentView.as_view(), name='email_confirm'),
    path('verify_email/<str:uidb64>/<str:token>/', UserVerifyEmailView.as_view(), name='verify_email'),
    path('email_confirmed/', UserConfirmedView.as_view(), name='email_confirmed'),

]

catalog/models.py
from django.conf import settings
from django.db import models
from django.utils.text import slugify

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')


    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)


class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')
    image = models.ImageField(upload_to='product/',verbose_name = 'изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    price = models.IntegerField(verbose_name='цена')
    creat_date = models.DateField(auto_now=True, verbose_name='дата создания')
    change_date = models.DateField(auto_now=True, verbose_name='дата последнего изменения')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='владелец')
    is_published = models.BooleanField(default=False, verbose_name='публикация продукта')

    def __str__(self):
        return f'{self.name} '

    @property
    def active_version(self):
        return self.version_set.get(current_version=True)

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('name',)


class Contacts(models.Model):
    name = models.CharField(max_length=255, verbose_name='имя')
    email = models.CharField(max_length=150, verbose_name='e-mail')
    message = models.TextField(**NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta():
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'



class Blog(models.Model):
    name = models.CharField(max_length=255, verbose_name='заголовок')
    slug = models.CharField(max_length=255, verbose_name='slug', unique=True)
    content = models.TextField(verbose_name='контент', **NULLABLE)
    image = models.ImageField(upload_to='blog/media/', verbose_name='превью', **NULLABLE)
    create_date = models.DateTimeField(auto_now=True, verbose_name='дата создания')
    is_published = models.BooleanField(default=True)
    view_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'{self.name}'


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    class Meta():
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'
        ordering = ('create_date',)



class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="продукт")
    version_num = models.IntegerField(default=0, verbose_name="номер версии")
    version_title = models.CharField(max_length=255, verbose_name="название версии")
    is_version = models.BooleanField(default=True)

    def __str__(self):
       return f'{self.version_title}'


    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class ProductForm(forms.ModelForm):

     def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        description = cleaned_data.get('description')
        censored_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for word in censored_words:
            if word in name.lower() or word in description.lower():
                raise forms.ValidationError(f'Запрещено использовать слово "{word}" в названии или описании продукта.')
        return cleaned_data

     def __init__(self, *args, **kwargs):
         super().__init__(*args, **kwargs)
         for field_name, field in self.fields.items():
             field.widget.attrs['class'] = 'form-control'

     class Meta:
         model = Product
         fields = '__all__'





class VersionForm(forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'


    #def clean_is_version(self):
    #    is_version = self.cleaned_data.get('is_version')
    #    product = self.cleaned_data.get('product')
#
    #    Version.objects.filter(product=product).exclude(id=self.instance.id).update(is_version=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.views import generic

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Contacts, Blog, Version


class IndexListView(generic.ListView):
    model = Product
    template_name = 'catalog/index.html'


class ProductListView(generic.ListView):
    model = Product

class ProductCreateView(LoginRequiredMixin, generic.CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:index')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner=self.request.user
        self.object.save()

        return super().form_valid(form)


    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST)
        else:
            formset = VersionFormset()

        context_data['formset'] = formset

        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = self.get_context_data()['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:index')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset

        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = self.get_context_data()['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def get_object(self, queryset=None):
        object = super().get_object(queryset)
        if object.owner != self.request.user:
            raise Http404("Вы не являетесь владельцем продукта.")
        return object

class ProductDetailView(generic.DetailView):
    model = Product


class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:index')

    def test_func(self):
        return self.request.user.is_superuser

class ContactsListView(generic.ListView):
    model = Contacts
    template_name = 'catalog/contact.html'


class BlogListView(generic.ListView):
    model = Blog
    queryset = Blog.objects.filter(is_published=True)


class BlogCreateView(generic.CreateView):
    model = Blog
    fields = ('name', 'content', 'image', 'is_published')
    success_url = reverse_lazy('catalog:blog_list')



class BlogDetailView(generic.DetailView):
    model = Blog

    def get_object(self, queryset=Blog):
        object = super().get_object()
        object.view_count += 1
        object.save()
        return object


class BlogUpdateView(generic.UpdateView):
    model = Blog

    fields = ['name', 'content', 'image']
    success_url = reverse_lazy('catalog:blog_list')

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('catalog:blog_detail', kwargs={'pk': pk})


class BlogDeleteView(generic.DeleteView):
    model = Blog
    success_url = reverse_lazy('catalog:blog_list')

#def product(request):
#    product_list = Product.objects.all()
#    content = {
#        'object_list': product_list
 #   }
 #   return render(request, 'catalog/product.html', content)


#def contacts(request):
#    return render(request, 'catalog/contact.html')

#def index(request):
#    product_list = Product.objects.all()
#    context = {
#        'object_list': product_list
#    }
#    return render(request, 'catalog/index.html', context)

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
      <title>Catalog</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">
  </head>

  <body>

    {% include 'catalog/includes/inc_main_menu.html' %}


    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">Catalog</h1>
            <p> Homework Django project Python-разработчик v3 </p>
        </div>
    </div>
    {% block content %}
    {% endblock %}


            <footer class="container">
      <p>&copy; &copy 2023 - {% now 'Y' %} </p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Удаление блога</h5>
      <form method="post">
        {% csrf_token %}
        Подтвердите удаление блога"{{ object.name }}"<br>
        <input type="submit" class="btn btn-outline-danger" value="Подтверждаю">
      </form>
      <div class="card-footer">
        <a href="{% url 'catalog:blog_list' %}" class="btn btn-primary"><< Назад</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load mytags %}
{% load static %}

{% block content %}
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="{% media_path blog.image %}" alt="Изображение недоступно"
                             width="304" height="228">
                        <div class="card-body">
                            <p class="card-text">{{ blog.name }}.</p>
                            <p class="card-text">{{ blog.content }}.</p>
                            <p class="card-text">{{ blog.create_date }}.</p>
                            <p class="card-text">Количество просмотров:{{ blog.view_count }}.</p>

                        </div>
                    </div>
                    <a href="{% url 'catalog:blog_list' %}" class="btn btn-primary"><< Назад</a>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% if object %} Изменить {% else %} Создать блог {% endif %}">
</form>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}
{% load mytags %}

{% block content %}

    <div class="album py-5 bg-light">
        <div class="button">
        <p><a class="btn btn-secondary" href="{% url 'catalog:blog_create' %}" role="button">Создать блог &raquo;</a></p>
            <div class="container">
                <div class="row">
                {% for blog in blog_list %}
                    <div class="col-md-4">
                        <div class="card mb-4 box-shadow" >
                             <img class="card-img-top" src="{% media_path blog.image %}" alt="Изображение недоступно">
                            <div class="card-body">
                            <p class="card-text">{{ blog.name }}.</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <p><a class="btn btn-secondary" href="{% url 'catalog:blog_detail' pk=blog.id %}" role="button">Подробнее &raquo;</a></p>
                                        <p><a class="btn btn-secondary" href="{% url 'catalog:blog_update' blog.id %}" role="button">Изменить &raquo;</a></p>
                                        <p><a class="btn btn-secondary" href="{% url 'catalog:blog_delete' blog.id %}" role="button">Удалить &raquo;</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                </div>
            </div>
        </div>
    </div>


{% endblock %}

catalog/templates/catalog/contact.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                    </form>
                    <input type="submit">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% load mytags%}
{% load static %}
{% block content %}

<div class="album py-5 bg-light">
        <div class="container">
            <div class="button">
                <p><a class="btn btn-secondary" href="{% url 'catalog:product_create' %}" role="button">Создать продукт &raquo;</a></p>
                <div class="row">
                    {% for object in object_list %}
                        <div class="col-md-4">
                            <div class="card mb-4 box-shadow">
                                <img class="card-img-top" src="{% media_path object.image %}" alt="Изображение недоступно" width="304" height="228">
                                <div class="card-body">
                                    <p class="card-text">{{ object }}{{ object.category }}.</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        {% if user.is_authenticated %}
                                         <div class="btn-group">
                                                    <p><a class="btn btn-secondary" href="{% url 'catalog:product_detail' pk=object.id %}" role="button">Подробнее &raquo;</a></p>
                                                    {% if perms.catalog.change_product %}
                                                    <p><a class="btn btn-secondary" href="{% url 'catalog:product_update' object.id %}" role="button">Изменить &raquo;</a></p>
                                                    {% endif %}
                                                    {% if user.is_superuser %}
                                                    <p><a class="btn btn-secondary" href="{% url 'catalog:product_delete' object.id %}" role="button">Удалить &raquo;</a></p>
                                                    {% endif %}
                                                </div>
                                        {% else %}

                                        {% endif %}
                                        <small class="text-muted">{{ object.creat_date}}</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>>
        </div>
</div>
{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load mytags %}
{% load static %}

{% block content %}
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">

                {% for object in object_list %}
                    <div class="col-md-4">
                                <div class="card mb-4 box-shadow">
                                    <img class="card-img-top" src="{% media_path object.image %}" alt="Изображение недоступно" width="304" height="228" >
                                        <div class="card-body">
                                            <p class="card-text">{{ object.name }}.</p>
                                            <p class="card-text">{{ object.category }}.</p>
                                            <p class="card-text">{{ object.description }}.</p>
                                            <p class="card-text">{{ object.price }}.</p>
                                            <p class="card-text">{{ object.creat_date }}.</p>
                                        </div>
                                </div>

                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Удаление продукта</h5>
      <form method="post">
        {% csrf_token %}
        Подтвердите удаление продукта"{{ object.name }}"<br>
        <input type="submit" class="btn btn-outline-danger" value="Подтверждаю">
      </form>
      <div class="card-footer">
        <a href="{% url 'catalog:index' %}" class="btn btn-primary"><< Назад</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load mytags %}
{% load static %}

{% block content %}
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="{% media_path product.image %}" alt="Изображение недоступно"
                             width="304" height="228">
                        <div class="card-body">
                            <p class="card-text">{{ product.name }}.</p>
                            <p class="card-text">{{ product.description }}.</p>
                            <p class="card-text">{{ product.creat_date }}.</p>
                            <p class="card-text">{{ product.price }}.</p>
                            {{ product.version.all }}
                            {% for version in product.version_set.all %}
                                <p class="card-text">
                                    {% if version.is_version %}
                                        Версия: {{ version.version_title }}
                                        Номер версии: {{ version.version_num }}
                                    {% endif %}
                                </p>

                            {%  endfor %}`

                        </div>
                    </div>
                    <a href="{% url 'catalog:product' %}" class="btn btn-primary"><< Назад</a>
                    {% if perms.catalog.change_product %}
                    <a href="{% url 'catalog:product_update' object.id %}" role="button">Изменить</a>
                    {% endif %}
                    {% if user.is_superuser  %}
                    <a href="{% url 'catalog:product_delete' object.id %}" role="button">Удалить</a>
                    {% endif %}
                </div>

            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Добавление продукта
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="{% if object %} Изменить {% else %} Создать продукт {% endif %}">
            </div>
            <div class="card-footer"></div>
        </div>
     </div>
        <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Версия продукта
                </h3>
            </div>
            <div class="card-body">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                    {{ form.as_p }}

                {% endfor %}
            </div>
            <div class="card-footer"></div>
        </div>
     </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load mytags %}
{% load static %}

{% block content %}
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">

                {% for object in object_list %}
                    <div class="col-md-4">
                                <div class="card mb-4 box-shadow">
                                    <img class="card-img-top" src="{% media_path object.image %}" alt="Изображение недоступно" width="304" height="228" >
                                        <div class="card-body">
                                            <p class="card-text">{{ object.name }}.</p>
                                            <p class="card-text">{{ object.category }}.</p>
                                            <p class="card-text">{{ object.description }}.</p>
                                            <p class="card-text">{{ object.price }}.</p>
                                            <p class="card-text">{{ object.creat_date }}.</p>
                                            <p class="card-text">{{ object.owner }}.</p>
                                            {% if user.is_authenticated %}
                                                <div class="btn-group">
                                                    <p><a class="btn btn-secondary" href="{% url 'catalog:product_detail' pk=object.id %}" role="button">Подробнее &raquo;</a></p>
                                                    {% if perms.catalog.change_product %}
                                                    <p><a class="btn btn-secondary" href="{% url 'catalog:product_update' object.id %}" role="button">Изменить &raquo;</a></p>
                                                    {% endif %}
                                                    {% if user.is_superuser %}
                                                    <p><a class="btn btn-secondary" href="{% url 'catalog:product_delete' object.id %}" role="button">Удалить &raquo;</a></p>
                                                    {% endif %}
                                                </div>
                                            {% else %}

                                            {% endif %}
                                        </div>
                                </div>

                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}